spring:
  jpa:
    hibernate:
      ddl-auto: none # none or valid
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  cookie:
    secure: true   # 배포환경
    same-site: Lax